version: '3.1'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - '${APP_PORT:-80}:80'
    volumes:
      - .:/var/www/html/
    depends_on:
      - mysql
    networks:
      - phplocal

  mysql:
    image: 'mysql:5.7'
    ports:
        - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
        MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
        MYSQL_DATABASE: '${DB_DATABASE}'
        # MYSQL_USER: '${DB_USERNAME}'
        MYSQL_PASSWORD: '${DB_PASSWORD}'
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - 'phplocalmysql:/var/lib/mysql'
    networks:
        - phplocal
    healthcheck:
        test: ['CMD', 'mysqladmin', 'ping']

networks:
    phplocal:
        driver: bridge

volumes:
    phplocalmysql:
        driver: local
